home_home:
    resource: "@HomeHomeBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

shop:
    resource: "@ShopBundle/Controller/"
    type:     annotation
    prefix:   /shop

market:
    resource: "@MarketBundle/Controller/"
    type:     annotation
    prefix:   /market

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /user


